### ISSUE TITLE
Crash if BrassAmberBattleTower is not installed

### ISSUE THREAD

**Issue by maximogta** [Samlegamer/Ageing-Spawners---Iaf-Battletower-Compat#1]
I just needed it for the Ice and Fire compat but it crashed while playing.
Latest forge and mods version.
https://pastebin.com/dZfjXvpz
It works fine if BrassAmberBattleTower is installed.

**Comment by Samlegamer** [comment]
You do not have BrassAmber BattleTower installed!
https://www.curseforge.com/minecraft/mc-mods/brassamberbattletowers
